// <auto-generated />
namespace Game_Uphoria.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class routing12 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(routing12));
        
        string IMigrationMetadata.Id
        {
            get { return "201512111746514_routing12"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
